name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install mkdocs-roamlinks-plugin mkdocs-meta-descriptions-plugin mkdocs-git-revision-date-localized-plugin mkdocs-ezlinks-plugin mkdocs-awesome-pages-plugin mkdocs-embed-file-plugins mkdocs-custom-tags-attributes mkdocs-callouts mkdocs-glightbox mdx-breakless-lists obsidiantools
      # - run: pip install mkdocs-mermaid2-plugin
      - run: mkdocs gh-deploy --force
